# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-12 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
            ],
        ),
    ]
